### ISSUE TITLE
Implement v0.2 CRD changes in the controller

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8-controller#156]
Acceptance criteria include unit tests, E2E-tests

**Comment by kimikowang** [comment]
For the changes to targetService, we will extend the definition of baseline/candidate as type obejctReference:
```
spec:
   targetService:
      name: name_of_servive
      namespace: namespace_of_service
      baseline: 
         apiVersion: v1(apps/v1)
         kind: Service(Deployment)
         name: name_of_service(name_of_baseline)
      candidate:
         apiVersion: v1(apps/v1)
         kind: Service(Deployment)
         name: name_of_service(name_of_baseline)
```

**Comment by sriumcp** [comment]
What is the difference between `targetService.name` on the one hand and `targetService.baseline.name` and `targetService.candidate.name` on the other? 

I can see the difference between them when baseline and candidates are deployments. But what happens if they are all services?

**Comment by fabolive** [comment]
**Reference use case 1: use of services for baseline and candidate**

```yaml
spec:
   targetService:
      name: reviews-baseline-svc
      apiVersion: v1
      kind: Service
      baseline: reviews-baseline-svc
      candidate: reviews-candidate-svc
```

**Comment by fabolive** [comment]
Reference use case 2: use of deployments for baseline and candidate

```yaml
spec:
   targetService:
      name: reviews
      apiVersion: apps/v1
      kind: Deployment
      baseline: reviews-v1
      candidate: reviews-v2
```

**Comment by fabolive** [comment]
Required parameter:
- `targetService.name`

Optional parameters and default values:
`targetService.apiVersion`: default value is `apps/v1`
`targetService.kind`: default value is `v1`

**Comment by fabolive** [comment]
We use `kind` to decide on the apiVersion for baseline/candidate.

**Comment by fabolive** [comment]
**Reference use case 3: Refer to an existing gateway**

```yaml
spec:
      gateways:
       - my-gateway
```
```

**Comment by fabolive** [comment]
**Reference use case 4: Refer to an _existing_ gateway and to an _existing_ virtual service**

```yaml
spec:
      gateways:
         - my-gateway
      routingReference:
         apiversion: networking.istio.io/v1alpha3
         kind: VirtualService
         name: reviews-external   
      targetService:
          apiVersion: v1
          name: reviews-baseline-svc
          kind: Service
          baseline: reviews-baseline-svc
          candidate: reviews-candidate-svc
```

In this case, the user probably already took care of the virtual service and its association with the gateway. I suppose iter8 will update the existing virtual service as needed for traffic management.

**Comment by fabolive** [comment]
**Reference use case 5: Refer to an _existing_ virtual service and to no gateway.**

This is the current support for edge services we have.

```yaml
spec:
      routingReference:
         apiversion: networking.istio.io/v1alpha3
         kind: VirtualService
         name: reviews-external   
      targetService:
          apiVersion: v1
          name: reviews-baseline-svc
          kind: Service
          baseline: reviews-baseline-svc
          candidate: reviews-candidate-svc
```

In this case, iter8 will update the existing virtual service as needed for traffic management and will not interfere with whatever gateway (if any) the virtual service has been associated with.
