### ISSUE TITLE
Manual design exercise for v0.2 through Istio

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8-controller#159]
Manually verify what is possible in Istio

**Comment by kimikowang** [comment]
I propose a gateway list should be added to spec.
```
spec:
    gateways: 
        - name: gw1
        - name: gw2
           namespace: ns2
```

A VirtualService can be attached to a list of gateways. 
The controller will try to get the gateways from cluster in the list. If it is not available, the controller will create one with default setting. (with host as wildcard match and http port 80 exposed)
