### ISSUE TITLE
Sample Experiment Object

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8-controller#97]
Sample CRs for v1.0.0 which demonstrate most of its new and important features

**Comment by sriumcp** [comment]
```
apiVersion: iter8.tools/v1alpha2 # Are we moving from v1alpha1 to v1alpha2?
kind: Experiment
metadata:
  name: reviews-v3-rollout
spec:
  serviceName: reviews
  baseline: reviews-v2
  # v1.0.0 will support only a list of size 1 (i.e., a single candidate, but this design makes it less likely that we will need to make breaking changes when we start supporting multiple candidates in the future)
  candidates: 
    - reviews-v3
  assessmentCriteria:
    - metricName: iter8_mean_latency
      threshold:
        type: absolute
        value: 25
    - metricName: iter8_error_rate
    - metricName: conversion_rate
  advancedTrafficControlParameters:
    interval: 30s
    maxIterations: 8
    strategy: simple_progressive_traffic_shift # mixing of cases here and elsewhere... is this ok?
    simpleProgressiveTrafficShiftParameters:
      stepSize: 20
      
```

**Comment by sriumcp** [comment]
**Pydantic datamodel for traffic control strategy:**

```
class Strategy(str, Enum):
    uniform = "Uniform Traffic Split"
    check_and_increment = "Simple Progressive Traffic Shift"
    epsilon_t_greedy = "Greedy Progressive Traffic Shift"
    pbr = "Bayesian Progressive Traffic Shift"
    # top_k_pbr = "Bayesian Rapid Rollout" # with a single candidate, top_k works in the same manner as uniform, so disabling this for now
```

**Comment by sriumcp** [comment]
```
apiVersion: iter8.tools/v1alpha2 # Are we moving from v1alpha1 to v1alpha2?
kind: Experiment
metadata:
  name: reviews-v3-rollout
spec:
  serviceName: reviews
  baseline: reviews-v2
  # v1.0.0 will support only a list of size 1 (i.e., a single candidate, but this design makes it less likely that we will need to make breaking changes when we start supporting multiple candidates in the future)
  candidates: 
    - reviews-v3
  assessmentCriteria:
    - metricName: iter8_mean_latency
      threshold:
        type: relative
        value: 1.1 # mean latency must be within 1.1 times baseline's mean latency
    - metricName: iter8_error_rate
    - metricName: conversion_rate
  analyticsServiceURL: http://iter8-analytics.iter8
  advancedTrafficControlParameters: # entire section is optional
    interval: 30s
    maxIterations: 8
    strategy: bayesian_progressive_traffic_shift
  advancedAssessmentParameters: # entire section is optional
    posteriorProbabilityForCredibleIntervals: 95.0
    minPosteriorProbabilityForWinner: 99.0    
```

**Comment by sriumcp** [comment]
```
apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: reviews-v3-rollout
spec:
  serviceName: reviews
  baseline: reviews-v2
  candidates: 
    - reviews-v3
  assessmentCriteria:
    - metricName: iter8_mean_latency
      threshold:
        type: relative # threshold for a ratio metric can be absolute or relative
        value: 1.1
    - metricName: iter8_error_rate
    - metricName: iter8_error_count
      threshold:
        type: absolute # counter metrics can have only absolute thresholds
        value: 10
        rollbackOnViolation: true # 10 errors and the candidate is out. This flag is supported only for counter metrics -- current limitation of this version. 
    - metricName: conversion_rate
  analyticsServiceURL: http://iter8-analytics.iter8
  advancedTrafficControlParameters:
    interval: 30s
    maxIterations: 8
    strategy: bayesian_progressive_traffic_shift
  advancedAssessmentParameters:
    posteriorProbabilityForCredibleIntervals: 95.0
    minPosteriorProbabilityForWinner: 99.0    
```

**Comment by sriumcp** [comment]
**Reward metric**
```
apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: reviews-v3-rollout
spec:
  serviceName: reviews
  baseline: reviews-v2
  candidates: 
    - reviews-v3
  assessmentCriteria:
    - metricName: iter8_mean_latency
      threshold:
        type: relative
        value: 1.1
    - metricName: iter8_error_rate
    - metricName: iter8_error_count
      threshold:
        type: absolute
        value: 10
        rollbackOnViolation: true
    - metricName: conversion_rate
         isReward: true # this is a reward metric. Only ratio metrics can be reward metrics. There can be at most one reward metric -- current limitation of this version.
  analyticsServiceURL: http://iter8-analytics.iter8
  advancedTrafficControlParameters:
    interval: 30s
    maxIterations: 8
    strategy: bayesian_progressive_traffic_shift
  advancedAssessmentParameters:
    posteriorProbabilityForCredibleIntervals: 95.0
    minPosteriorProbabilityForWinner: 99.0    
```

**Comment by sriumcp** [comment]
@fabolive @kimikowang @sushmarchandran @kalantar 

Could we please get a discussion started here on the sample experiment CRs for v1.0.0. Obviously these CRs are intended to be initial samples and can be reshaped based on our discussions.

At the moment -- these experiment CRs impact only the controller (i.e., automated experiments). It is unclear if they have an impact on HIL experiments (at the moment, no).

**Comment by fabolive** [comment]
> **Basic example. Versioning?**
> 
> ```
> apiVersion: iter8.tools/v1alpha2 # Are we moving from v1alpha1 to v1alpha2?

We could move to `v1alpha2`. There a bigger question here. When defining the CRD schema, one can declare all versions that are supported by the controller. We need to think carefully about this and look for best-practice guidance. Perhaps it is okay to change the controller code in our release v1.0.0 to not be backwards compatible.

**Comment by fabolive** [comment]
> **Optional advanced sections. Mixed cases ok?**
> 

I am fine with camelCase for attribute names and snake_case for values. Any objections?

**Comment by kimikowang** [comment]
```
apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
     name: reviews-v3-rollout
spec:
    # required
    service:
        name: reviews
        apiVersion: v1
        baseline: reviews-v2
        candidates: 
        - reviews-v3
    # optional
    trafficControl:
       interval: 30s
       maxIterations: 8
       strategy: 
           name: bayesian_progressive_traffic_shift
           # optional; can be any key-value pairs, just like how we specify labels
           params: 
               stepSize: 5
   # optional
   analysis:
       # optional
       analyticsEndopint: http://iter8-analytics.iter8
       assessment:
           # optional
           posteriorProbabilityForCredibleIntervals: 95.0
           # optional
           minPosteriorProbabilityForWinner: 99.0    
           criteria:
              - metric: iter8_mean_latency
                 threshold:
                     type: relative
                     value: 1.1
              - metric: iter8_error_rate
              - metric: iter8_error_count
                 threshold:
                    type: absolute
                    value: 10
                 rollbackOnViolation: true
              - metric: conversion_rate
                 isReward: true
```

@sriumcp This is the sample cr reflecting what I imagine. In my opinion, it's better to group the parameters for one type instead of specifying them in different places. For advanced settings, we just need to make those parameters as optional.

**Comment by sriumcp** [comment]
@kimikowang Interesting.. do we want `criteria` to be optional?

Are there use cases where we might want to create an experiment with no criteria?

**Comment by kimikowang** [comment]
Yes, the controller supports `increment_without_check` strategy.

**Comment by sriumcp** [comment]
Yes, for testing purposes. But is this a strategy we want the user to use?

**Comment by kimikowang** [comment]
I am not sure, but this is good for testing. We can regard it as an internal feature.

**Comment by sriumcp** [comment]
My thinking is that `criteria` is not at the same level as `minPosteriorProbabilityForWinner`.

The former seems very basic and important and something most users will want to specify. The latter, `minPosteriorProbabilityForWinner` is so obscure that most users will not even understand this and leave it alone. This was the reason why I pulled out the criteria and bundled these more obscure options inside the advancedOptions section... 

I am actually ok with 4 sections under spec, `service`, `trafficControl`, `criteria`, `analysis`. I feel that `criteria` is important enough for most users to be at the same level as these other things...

**Comment by sriumcp** [comment]
On `increment_without_check` -- yes, I see value in doing this (e.g., the user might want to do manual assessment with automated traffic shifting).

But I think the way we will want to surface it to the user is through `check_and_increment` with no `criteria` (instead of providing another user-visible strategy). Of course, internally, in this case, the controller can choose to implement it using `increment_without_check` without ever calling the analytics service.

**Comment by kimikowang** [comment]
I think decision of placing fields is based on definition, not importance. Putting `criteria` inside `analysis` does not indicate that the former one is not as important as `analysis`, but reveals that `criteria` is the factor that will affect the `analysis` result. Making `criteria` a required field in `analysis` shows its importance in the computation, compared to other optional parameters.

Right now, the controller will switch to `increment_without_check` automatically  without seeing criteria specified. So this is why I called it an internal feature.

@sriumcp

**Comment by sriumcp** [comment]
@kimikowang Lets compare how the two proposals work for a canary release scenario, where the user goes with iter8's defaults for all the advanced options.

The user wants to rollout a canary based on a couple of thresholds + a couple of other (plainly monitored) metrics.

*Experiment object as per the original proposal*

```
apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
     name: reviews-v3-rollout
spec:
    # required
    service:
        name: reviews
        apiVersion: v1
        baseline: reviews-v2
        candidates: 
        - reviews-v3
    criteria:
      - metric: iter8_mean_latency
        threshold:
           type: relative
           value: 1.1
      - metric: iter8_error_rate
      - metric: iter8_error_count
        threshold:
           type: absolute
           value: 10
           rollbackOnViolation: true
      - metric: conversion_rate
        isReward: true
```

*Experiment object as per the revised proposal*

```
apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
     name: reviews-v3-rollout
spec:
    # required
    service:
        name: reviews
        apiVersion: v1
        baseline: reviews-v2
        candidates: 
        - reviews-v3
    analysis:
        assessment:
          criteria:
            - metric: iter8_mean_latency
              threshold:
                 type: relative
                 value: 1.1
            - metric: iter8_error_rate
            - metric: iter8_error_count
              threshold:
                 type: absolute
                 value: 10
                 rollbackOnViolation: true
            - metric: conversion_rate
              isReward: true
```

I feel the original proposal is better from the user's perspective because there is less typing involved and experiment object looks simpler (I also think this scenario is going to a frequent scenario for iter8).

This is the reason why I am reluctant to move from the original proposal to the revised proposal.

**Comment by sriumcp** [comment]
Re: `increment_without_check` -- yes, we are in agreement. 

It doesn't affect our discussion above re: the two proposals since criteria doesn't enter into the picture at all in this scenario.

**Comment by fabolive** [comment]
Consider expressing unit in absolute threshold specification.

**Comment by sriumcp** [comment]
**Reward metric**
```
apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: reviews-v3-rollout
spec:
  serviceName: reviews
  baseline: reviews-v2
  candidates: 
    - reviews-v3
  criteria:
    - metricName: iter8_mean_latency
      threshold:
        type: relative
        value: 1.1
    - metricName: iter8_error_rate
    - metricName: iter8_error_count
      threshold:
        type: absolute
        value: 10
        rollbackOnViolation: true
    - metricName: conversion_rate
         isReward: true # this is a reward metric. Only ratio metrics can be reward metrics. There can be at most one reward metric -- current limitation of this version.
  advancedParameters:
    analyticsServiceURL: http://iter8-analytics.iter8
    trafficControlParameters:
      interval: 30s
      maxIterations: 100
      stepSize: 2.0
      explorationTrafficPercentage: 5.0
      strategy: "Progressive Rollout"
      experimentTrafficPercentage: 20.0 # 20 percent of requests that match will be used for experimentation
      match: # everything which Istio allows under its match clause is allowed here
      - headers:
          end-user:
            exact: jason
    advancedAssessmentParameters:
      posteriorProbabilityForCredibleIntervals: 95.0
      minPosteriorProbabilityForWinner: 99.0    
```

**Comment by sriumcp** [comment]
@fabolive @kimikowang 

I am still in the process of tweaking the `advancedParameters` section of the sample CRs... 

Could I request your comment on the`match` section above? I know this is not in scope for release `v1.0.0`, but I wanted to introduce this with the intent of making it a bit more future proof.

The idea is that `match` section will support all the settings which Istio's match clause support.

**Comment by fabolive** [comment]
@sriumcp: The match clause above is probably okay. 

On a different note, do not forget to consider having the user specify the unit for absolute thresholds, e.g.:

```yaml
- metricName: iter8_error_count
      threshold:
        type: absolute
        value: 10ms
```

**Comment by sriumcp** [comment]
@fabolive I did consider the units, but specifically decided against it.

I don't think we should make iter8 units aware internally in its computations.

First, this is a highly non-trivial feature with potential for numerous bugs... in your own example above, iter8_error_count doesn't have units (it is a number with no units), although latency does have units, so it is unclear what type of error iter8 should throw after seeing `ms` above :)

Second, units should be specified in one place for a metric -- the natural place for that is the ConfigMap (with the understanding that absolute thresholds share the same units as the underlying metric for which the units are specified).

Third, we. can still use the `msec` units for latency everywhere in the English text / interpretations. For e .g., the controller output, kiali, and KUI can also say, candidate latency failed to satisfy the threshold of 2 msec. If  the user intended 2 sec instead of 2 msec, they can detect it visually and fix their threshold specs. Also, we can provide helpful annotations in KUI / Kiali (using the units specified in ConfigMap) so that the chances of user making unit errors of this type are minimized.

**Comment by sriumcp** [comment]
**Add action, termination / cleanup, and routing reference clauses to example.**

**Comment by kalantar** [comment]
@sriumcp:
What are `advancedParameters.trafficControlParameters.experimentTrafficPercentage` and `advancedParameters.trafficControlParameters.explorationTrafficPercentage`; what is the difference?
What is `advancedParameters.trafficControlParameters.strategy` and what are valid values?
What is `advancedParameters.rollforwardStrategy` and what are valid values?

**Comment by sriumcp** [comment]
# Current version after the latest edits

```
apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: reviews-v3-rollout
spec:
  serviceName: reviews
  apiVersion: v1 # shouldn't this be optional with a sensible default?
  baseline: reviews-v2 # baseline deployment
  candidates: # list of one or more candidate deployments
    - reviews-v3

  # routingReference is a reference to an existing Istio VirtualService (optional section)
  # this should be used only if an Istio VirtualService has already been defined for the target Kubernetes service
  routingReference:
    apiversion: networking.istio.io/v1alpha3
    kind: VirtualService
    name: reviews-external

  # This section contains a list of assessment criteria (optional section)
  # However, we expect all but toy experiments to have one or more criteria
  criteria: 
    - metricName: iter8_mean_latency
      threshold: # (optional section)
        type: relative # can be relative or absolute
        value: 1.1 # float
    - metricName: iter8_error_rate
    - metricName: iter8_error_count
      threshold:
        type: absolute
        value: 10
        rollbackOnViolation: true # if the threshold is violated, the candidate is rolled back (optional)
    - metricName: conversion_rate
        isReward: true # this is a reward metric. Only ratio metrics can be reward metrics. There can be at most one reward metric (optional)

  # This section pertains to duration of the experiment (optional section)
  duration:
    interval: 30s # default value (optional)
    maxIterations: 100 # default value (optional)

  # This section allows manual interventions in the middle of an ongoing experiment (optional section)
  # The user changes this section and reapply the experiment object
  manualOverrides: 
    action:  pause # resume, rollforward, rollback are other options
    # candidate name is ignored if action is not rollforward. 
    # If action is rollforward and if there is only a single candidate, this field is optional
    # If action is rollforward and there are multiple candidates, this field is mandatory
    candidate: review-v3

  # This section pertains to automated control of traffic during an experiment (optional section)
  trafficControl:
    experimentTrafficPercentage: 20.0 # 20 percent of requests that match will be used for experimentation (optional: default = 100.0)
    match: # same as Istio's match clause (optional section)
    - headers:
        end-user:
          exact: jason
    stepSize: 2.0 # default value. Never increase a candidate's traffic percentage allocation beyond step size in any single iteration (optional)
    strategy: "progressive_traffic_shift" # default value. Other options are "top_2" and "uniform" (optional)
  
  # This field pertains to actions performed by iter8 after termination of an experiment (optional)
  onTermination: keep_winning_version # other options are keep_all_versions, keep_all_versions_and_traffic_split

  # iter8 analytics service URL used by iter8 controller  
  analyticsServiceURL: http://iter8-analytics.iter8 (optional)
```

**Comment by sriumcp** [comment]
@kalantar Hopefully, the above experiment object with comments answers your questions. I removed some of the parameters all together -- I don't think we need to expose them to the user just yet (they will be internal to the analytics service).

**Comment by kalantar** [comment]
@sriumcp looks good!

**Comment by fabolive** [comment]
@sriumcp: Looks good to me. Only one additional point: we might add a comment to the effect that the behavior resulting from `removeCandidate`  will take into consideration the `cleanupVersions` flag.

**Comment by huang195** [comment]
Is there a section on summary metric data that Iter8-trend could use instead of having to get data from Prometheus. I think we talked about this 2 weeks ago. Maybe I missed it from a quick glance of the current data format

**Comment by sriumcp** [comment]
@huang195  Short answer = yes. However, this feature is still under design / construction, so might be ready in a couple of weeks for a preview.

**Comment by sriumcp** [comment]
Also -- this is the experiment object which the user applies. However, the current state of the experiment will end up containing the stats you're interested in.

**Comment by huang195** [comment]
Good to know. This is good to have for iter8-trend as it will reduce traffic to Prometheus.

**Comment by sriumcp** [comment]
Trial 1:  
```
manualOverrides: 
    action:  pause # resume, rollbackToBaseline, rollforwardToCandidate, removeCandidate are other options
    # candidate field is ignored unless action is rollforwardToCandidate or removeCandidate. 
    # for rollforwardToCandidate and removeCandidate actions, if there is only a single candidate, this field is optional
    # for rollforwardToCandidate and removeCandidate actions, if there are multiple candidates, this field is mandatory
    candidate: review-v3
```

vs.
Trial 2
```
action:
  do: terminate # pause, resume
  # no options for pause and resume
  options: # if clean up is true, get ride of everything else that doesn't get traffic
    reviews-v3: 20
    reviews-v2: 80
```

also

```
action:
  do: terminate # pause, resume
  # no options for pause and resume
  options: # if clean up is true, get ride of everything else that doesn't get traffic
    reviews-v3: 100 # roll forward to reviews-v3
```

also 

```
action:
  do: terminate # pause, resume
  # no options for pause and resume
  options: # if clean up is true, get ride of everything else that doesn't get traffic
    reviews-v2: 100 # rollback to baseline which is reviews-v2
```

vs.
Trial 3

```
manualOverride:
  action: terminate # pause, resume
  # no options for pause and resume
  options: # if clean up is true, get ride of everything else that doesn't get traffic
    reviews-v3: 20
    reviews-v2: 80
```

also

```
manualOverride:
  action: terminate # pause, resume
  # no options for pause and resume
  options: # if clean up is true, get ride of everything else that doesn't get traffic
    reviews-v3: 100 # roll forward to reviews-v3
```

also 

```
manualOverride:
  action: terminate # pause, resume
  # no options for pause and resume
  options: # if clean up is true, get ride of everything else that doesn't get traffic
    reviews-v2: 100 # rollback to baseline which is reviews-v2
```

vs.
Trial 4

```
override: terminate # pause, resume
# no options for pause and resume
overrideOptions: # if clean up is true, get ride of everything else that doesn't get traffic
  reviews-v3: 20
  reviews-v2: 80
```

also

```
override: terminate # pause, resume
# no options for pause and resume
overrideOptions: # if clean up is true, get ride of everything else that doesn't get traffic
  reviews-v3: 100 # roll forward to reviews-v3
```

also 

```
override: terminate # pause, resume
# no options for pause and resume
overrideOptions: # if clean up is true, get ride of everything else that doesn't get traffic
  reviews-v2: 100 # rollback to baseline which is reviews-v2
```

**Trial 4 has won. We will use this! **

**Comment by kimikowang** [comment]
On specifications on Service, as what we did in v1alpha1, name/apiversion/baseline/candidate can be defined under a field called `service`, which can give a clearer definition. We can interpret this as: baseline and candidates are deployments behind a service, which can be referred as name/namespace/apiVersion...(all are attributes of ObjectReference https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L5053). Noticed that all the fields are optional. 

```
spec:
  service:
    name: reviews
    apiVersion: v1
    namespace: booking-iter8
    baseline: reviews-v2
    candidates:
      - reviews-v3
      - reviews-v4
```
