### ISSUE TITLE
Sample metric specs

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8-controller#98]

**Comment by sriumcp** [comment]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: iter8config-metrics
  namespace: {{ .Values.namespace }}
  annotations:
    version: 1.0.0 # metric crd version
data: # by convention, metrics with names beginning with iter8_ are defined by iter8
  counter_metrics: # a counter metric is monotonically increasing or decreasing
    - name: iter8_request_count
      query_template: sum(increase(istio_requests_total{reporter='source'}[$interval])) by ($entity_labels)
    - name: iter8_total_latency
      query_template: sum(increase(istio_request_duration_seconds_sum{reporter='source'}[$interval]$offset_str)) by ($entity_labels)
    - name: iter8_error_count
      query_template: sum(increase(istio_requests_total{response_code=~'5..',reporter='source'}[$interval])) by ($entity_labels)
      preferred_direction: lower # preferred_direction must be specified in order to use thresholds
    - name: conversion_count # user defined
      query_template: sum(increase(newsletter_signups[$interval])) by ($entity_labels)
  ratio_metrics: # the value of a ratio metric equals value of numerator divided by denomenator 
    - name: iter8_mean_latency
      numerator: iter8_total_latency
      denomenator: iter8_request_count
      preferred_direction: lower # lower mean latency is preferable to higher mean latency
    - name: iter8_error_rate
      numerator: iter8_error_count
      denomenator: iter8_request_count
      preferred_direction: lower
      unit_range: true # metric is always between 0 and 1
    - name: conversion_rate # user defined
      numerator: conversion_count
      denomenator: iter8_request_count
      preferred_direction: higher
      unit_range: true
```

**Comment by sriumcp** [comment]
@Alan-Cha  @sushmarchandran @kimikowang @jadeyliu939 @kalantar @fabolive 

If you notice any issues with the metric specs configmap above... could you please let me know by commenting on this issue? If there are no comments -- we can, at least for now, agree on this configmap, and move on.

I believe I've handled all the comments I received so far (from our discussions).

**Comment by fabolive** [comment]
Looks good to me, @sriumcp.

**Comment by sriumcp** [comment]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: iter8config-metrics
  namespace: {{ .Values.namespace }}
  annotations:
    version: 1.0.0 # metric spec version
data: # by convention, metrics with names beginning with iter8_ are defined by iter8
  # a counter metric is monotonically increasing or decreasing
  counter_metrics.yaml: |- 
    - name: iter8_request_count
      query_template: sum(increase(istio_requests_total{reporter='source'}[$interval])) by ($version_labels)
    - name: iter8_total_latency
      query_template: sum(increase(istio_request_duration_seconds_sum{reporter='source'}[$interval])) by ($version_labels)
      base_unit_of_measurement: msec # optional
    - name: iter8_error_count
      query_template: sum(increase(istio_requests_total{response_code=~'5..',reporter='source'}[$interval])) by ($version_labels)
      preferred_direction: lower # preferred_direction must be specified in order to use thresholds
    - name: conversion_count # user defined
      query_template: sum(increase(newsletter_signups[$interval])) by ($version_labels)
  # the value of a ratio metric equals value of numerator divided by denominator 
  ratio_metrics.yaml: |- 
    - name: iter8_mean_latency
      numerator: iter8_total_latency
      denominator: iter8_request_count
      preferred_direction: lower # lower mean latency is preferable to higher mean latency
    - name: iter8_error_rate
      numerator: iter8_error_count
      denominator: iter8_request_count
      preferred_direction: lower
      between_zero_and_one: true # metric is always between 0 and 1
    - name: conversion_rate # user defined
      numerator: conversion_count
      denominator: iter8_request_count
      preferred_direction: higher
      between_zero_and_one: true
```

**Comment by sriumcp** [comment]
@fabolive @sushmarchandran What do you think? I updated to above based on our discussion on units!

**Comment by fabolive** [comment]
@sriumcp: Will iter8-analytics' code make use of the unit of measurement? If so, how? If not, will that attribute be purely informative?

**Comment by sriumcp** [comment]
@fabolive `iter8-analytics` will not make use of it. However, controller and kiali can make use of them while displaying information about metric values.

**Comment by fabolive** [comment]
Let's discuss the implications of the incorporation of the units into the CRD design.

**Comment by fabolive** [comment]
Consider renaming `base_unit_of_measurement` to something less verbose.

**Comment by sriumcp** [comment]
@fabolive Done. I also renamed `between_zero_and_one` to `zero_to_one` to make it less verbose.

**Comment by kalantar** [comment]
What are valid values for `units`?

**Comment by sriumcp** [comment]
@kalantar `units` is optional. It is not used by the analytics service or the controller (at least at the moment, that's the intent). The value of a metric is calculated using values returned by prometheus, and although it is not specified in Prometheus, there is an underlying unit of measurement for many metrics. The idea behind `units` is to capture this unit of measurement specifically.

For e.g., prometheus used to report latency pre istio 1.4 in sec (so units would be sec in that case). In Istio 1.5+, it apparently reports latency in msec. So these are the respective units.

Kiali / KUI can use this while displaying information (e.g., kiali in its displays can say that iter8_mean_latency is within the threshold of 200 msec), where 200 is the user supplied threshold as part of experiment spec, and msec is the user supplied `units` in the config_map (since this is an iter8 default, we will supply units here).

Any string is syntactically acceptable for units. However, garbage strings will result in garbage output in Kiali / KUI.

**Comment by sriumcp** [comment]
@kalantar Here's the mapping back to the older `v0.0.1` metrics specs like you wanted... 

I am not sure doing this conversion automatically is a good idea. I think it is ok to simply say `v1.0.0` is a clean break from `v0.0.1` and simply have two versions (if needed). Anyway, here it is... 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: iter8config-metrics
  namespace: {{ .Values.namespace }}
  annotations:
    version: 1.0.0 # metric spec version
data: # by convention, metrics with names beginning with iter8_ are defined by iter8
  # a counter metric is monotonically increasing or decreasing
  counter_metrics.yaml: |- 
    - name: iter8_request_count
      query_template: sum(increase(istio_requests_total{reporter='source'}[$interval])) by ($version_labels)
    - name: iter8_total_latency
      query_template: sum(increase(istio_request_duration_seconds_sum{reporter='source'}[$interval])) by ($version_labels)
      units: msec # optional
    - name: iter8_error_count
      query_template: sum(increase(istio_requests_total{response_code=~'5..',reporter='source'}[$interval])) by ($version_labels)
      preferred_direction: lower # preferred_direction must be specified in order to use thresholds
    - name: conversion_count # user defined
      query_template: sum(increase(newsletter_signups[$interval])) by ($version_labels)
  # the value of a ratio metric equals value of numerator divided by denominator 
  ratio_metrics.yaml: |- 
    - name: iter8_mean_latency
      numerator: iter8_total_latency
      denominator: iter8_request_count
      preferred_direction: lower # lower mean latency is preferable to higher mean latency
    - name: iter8_error_rate
      numerator: iter8_error_count
      denominator: iter8_request_count
      preferred_direction: lower
      zero_to_one: true # metric is always between 0 and 1
    - name: conversion_rate # user defined
      numerator: conversion_count
      denominator: iter8_request_count
      preferred_direction: higher
      zero_to_one: true
```

**becomes like below in the older version... **

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: iter8config-metrics
  namespace: {{ .Values.namespace }}
data:
  query_templates: |-
    iter8_request_count: "sum(increase(istio_requests_total{reporter='source'}[$interval])) by ($entity_labels)"
    iter8_total_latency: "sum(increase(istio_request_duration_seconds_sum{reporter='source'}[$interval])) by ($entity_labels)"
    iter8_mean_latency: "(sum(increase(istio_request_duration_seconds_sum{reporter='source'}[$interval])) by ($entity_labels)) / (sum(increase(istio_requests_total{reporter='source'}[$interval])) by ($entity_labels))"
    iter8_error_count: "sum(increase(istio_requests_total{response_code=~'5..',reporter='source'}[$interval])) by ($entity_labels)"
    iter8_error_rate: "sum(increase(istio_requests_total{response_code=~'5..',reporter='source'}[$interval])) by ($entity_labels) / sum(increase(istio_requests_total{reporter='source'}[$interval])) by ($entity_labels)"
    conversion_count: "sum(increase(newsletter_signups[$interval])) by ($entity_labels)"
    conversion_rate: "sum(increase(newsletter_signups[$interval])) by ($entity_labels) / sum(increase(istio_requests_total{reporter='source'}[$interval])) by ($entity_labels)"
  metrics: |-
    - name: iter8_request_count
      is_counter: True
      sample_size_query_template: iter8_request_count
    - name: iter8_total_latency
      is_counter: True
      sample_size_query_template: iter8_request_count
    - name: iter8_error_count
      is_counter: True
      sample_size_query_template: iter8_request_count
    - name: conversion_count
      is_counter: True
      sample_size_query_template: iter8_request_count
    - name: iter8_mean_latency
      is_counter: False
      absent_value: "None"
      sample_size_query_template: iter8_request_count
    - name: iter8_error_rate
      is_counter: False
      absent_value: "None"
      sample_size_query_template: iter8_request_count
    - name: conversion_rate
      is_counter: False
      absent_value: "None"
      sample_size_query_template: iter8_request_count
```
